### ISSUE TITLE
✨ [Feat] 테스트 케이스 작성

### ISSUE THREAD

**Issue by kyeon06** [kyeon06/django-cafe-manager#4]
## Description

API 테스트를 위해 테스트 케이스를 작성한다.

## Todo
- [ ] 회원가입 테스트
- [ ] 로그인 테스트
- [ ] 상품 등록 테스트
- [ ] 상품 삭제 테스트
- [ ] 상품 조회 테스트
- [ ] 상품 수정 테스트
- [ ] 상품 검색 테스트

## ETC
기타 사항
